function y = MineExtraction_Y(t,a,T,x0)
%MineExtraction_Y
%    Y = MineExtraction_Y(t,A,T,X0)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    11-Apr-2024 11:46:18

t2 = T.*a;
y = x0.*1.0./(t2+4.0).^2.*(t2-a.*t+4.0).^2;
end
