function u = AndersonMoore64_U(t,t0,tf,x0)
%ANDERSONMOORE64_U
%    U = ANDERSONMOORE64_U(T,T0,TF,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Dec-2017 10:16:20

t2 = exp(-tf);
t3 = exp(t);
u = (x0.*(exp(t-tf)+1.0).*(t2.*t3.*(1.0./2.0)-1.0./2.0))./((exp(t0-tf)+1.0).*(t2.*t3+1.0));
