function u = TurnerChunJuang1_U(S,a,em,eta,f,t,t0,um,y0)
%TURNERCHUNJUANG1_U
%    U = TURNERCHUNJUANG1_U(S,A,EM,ETA,F,T,T0,UM,Y0)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    11-Apr-2019 14:11:21

t2 = um.^2;
t3 = 1.0./S;
t4 = 1.0./a;
t6 = 1.0./em.^2;
t7 = -t;
t8 = -t0;
t5 = t4.^2;
t9 = 1.0./t2;
t10 = f+t7;
t11 = f+t8;
t12 = -t4;
t13 = t2.*t6;
t14 = t5+t13;
t15 = 1.0./t14;
t16 = sqrt(t14);
t17 = t10.*t16;
t18 = t11.*t16;
t19 = t12+t16;
t20 = -t9.*(t4-t16);
t21 = t9.*(t4-t16);
t22 = S+t21;
t23 = t3.*t20;
t26 = -1.0./(t3.*t21+1.0);
t24 = t23-1.0;
t25 = 1.0./t22;
t27 = t9.*t16.*t25.*2.0;
t28 = t27+1.0;
t29 = log(t28);
t31 = 1.0./sqrt(t28);
t30 = t29./2.0;
t32 = cosh(t30);
t33 = t17+t30;
t34 = t18+t30;
t35 = cosh(t33);
t36 = coth(t34);
t37 = sinh(t33);
t38 = sinh(t34);
t39 = 1.0./t38;
u = t4.*(t37.*t39.*y0-eta.*t13.*t15.*(t32.*t35+t37.*t39-t32.*t36.*t37-1.0)+(eta.*t31.*(t35-t36.*t37))./(t3.*t21+1.0))+eta.*t26.*t31.*(t16.*t37-t16.*t35.*t36)-t16.*t35.*t39.*y0+eta.*t13.*t15.*(t16.*t32.*t37+t16.*t35.*t39-t16.*t32.*t35.*t36);
