function y = TurnerChunJuang1_Y(S,a,em,eta,f,t,t0,um,y0)
%TURNERCHUNJUANG1_Y
%    Y = TURNERCHUNJUANG1_Y(S,A,EM,ETA,F,T,T0,UM,Y0)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    11-Apr-2019 14:11:20

t2 = um.^2;
t3 = 1.0./a;
t5 = 1.0./em.^2;
t6 = -t;
t7 = -t0;
t4 = t3.^2;
t8 = 1.0./t2;
t9 = f+t6;
t10 = f+t7;
t11 = -t3;
t12 = t2.*t5;
t13 = t4+t12;
t14 = sqrt(t13);
t15 = t9.*t14;
t16 = t10.*t14;
t17 = t11+t14;
t18 = -t8.*(t3-t14);
t19 = t8.*(t3-t14);
t20 = S+t19;
t21 = 1.0./t20;
t22 = t8.*t14.*t21.*2.0;
t23 = t22+1.0;
t24 = log(t23);
t25 = t24./2.0;
t26 = cosh(t25);
t27 = t15+t25;
t28 = t16+t25;
t29 = cosh(t27);
t30 = coth(t28);
t31 = sinh(t27);
t32 = sinh(t28);
t33 = 1.0./t32;
y = t31.*t33.*y0-eta.*t12.*1.0./t14.^2.*(t26.*t29+t31.*t33-t26.*t30.*t31-1.0)+(eta.*1.0./sqrt(t23).*(t29-t30.*t31))./(t19./S+1.0);
