function I = BrysonHo116_F(tf,v0,x0)
%BRYSONHO116_F
%    I = BRYSONHO116_F(TF,V0,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Dec-2017 14:51:09

t2 = tf-v0;
I = tf-sqrt(x0.*-4.0+t2.^2-v0.^2.*2.0);
