function I = BettsBiehnCampbell1_F
%BETTSBIEHNCAMPBELL1_F
%    I = BETTSBIEHNCAMPBELL1_F

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    17-Dec-2017 22:39:24

I = 3.122657235001562e2;
