function I = Hager1_F
%HAGER1_F
%    I = HAGER1_F

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Dec-2017 12:20:31

I = exp(-2.0).*(exp(4.0)-1.0).*1.049935854035065e-1;
