function out1 = Biegler9p5_Y(t)
%Biegler9p5_Y
%    OUT1 = Biegler9p5_Y(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    02-Apr-2024 21:44:03

t2 = t.*pi;
out1 = [sin(t2),pi.*cos(t2)];
end
