function x = DTQP2_Y(A,B,M,R,t,tf,w,x0)
%DTQP2_Y
%    X = DTQP2_Y(A,B,M,R,T,TF,W,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Jan-2018 23:10:01

t2 = A.^2;
t3 = w.^2;
t4 = B.^2;
t5 = tf.*w.*2.0;
t6 = A.*t.*2.0;
t7 = exp(t6);
t8 = A.*tf.*2.0;
t9 = exp(t8);
t10 = M.*t3.*t4.*t9;
t11 = cos(t5);
t12 = sin(t5);
t13 = t.*w.*2.0;
x = (x0.*exp(-A.*t).*(t10-M.*t2.*t4.*t7-M.*t3.*t4.*t7+M.*t2.*t4.*t9+A.*R.*t2.*t7.*4.0+A.*R.*t3.*t7.*4.0+M.*t2.*t4.*t7.*t11-M.*t2.*t4.*t9.*cos(t13)+A.*M.*t4.*t9.*w.*sin(t13)-A.*M.*t4.*t7.*t12.*w))./(t10+A.*R.*t2.*4.0+A.*R.*t3.*4.0-M.*t2.*t4-M.*t3.*t4+M.*t2.*t4.*t11-A.*M.*t4.*t12.*w);
