function u = BrysonHo248_U(a,b,c,t,t1,t2,tf)
%BRYSONHO248_U
%    U = BRYSONHO248_U(A,B,C,T,T1,T2,TF)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    11-Apr-2018 21:31:56

t4 = a.*2.0;
t5 = b.*t1.*2.0;
t6 = t1.^2;
t7 = t-t1;
t8 = heaviside(t7);
t9 = c.*t1.*2.0;
t10 = t-t2;
t11 = heaviside(t10);
u = -c.*(t11-heaviside(t-tf))-(exp(-t).*exp(t1).*(t4+t5+t9-c.*t6).*(1.0./4.0)+exp(-t1).*exp(t).*(b.*4.0+t4+t5-t9-c.*t6).*(1.0./4.0)).*(t8-t11)-c.*(t8-1.0);
