function u = Hager1_U(t)
%HAGER1_U
%    U = HAGER1_U(T)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Dec-2017 12:20:31

u = exp(-t+1.0).*(exp(t.*2.0-2.0)-3.0).*1.620135684159713e-1;
