function out1 = BrysonHo156_Y(c,t,t0,tf,v0,w,x0)
%BRYSONHO156_Y
%    OUT1 = BRYSONHO156_Y(C,T,T0,TF,V0,W,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Dec-2017 11:48:06

t2 = w.^2;
t3 = t-t0;
t4 = t3.*w;
t5 = sin(t4);
t9 = tf.*2.0;
t6 = t+t0-t9;
t7 = t6.*w;
t8 = sin(t7);
t10 = cos(t4);
t11 = cos(t7);
t12 = t0-tf;
t13 = t12.*w.*2.0;
t14 = sin(t13);
t15 = c.*t14;
t16 = t2.*w.*4.0;
t17 = c.*tf.*w.*2.0;
t18 = t15+t16+t17-c.*t0.*w.*2.0;
t19 = 1.0./t18;
out1 = [t19.*(c.*t5.*x0+c.*t8.*x0+t2.*t5.*v0.*4.0-c.*t.*t5.*v0-c.*t0.*t5.*v0+c.*t.*t8.*v0-c.*t0.*t8.*v0+c.*t5.*tf.*v0.*2.0+t2.*t10.*w.*x0.*4.0-c.*t.*t10.*w.*x0-c.*t0.*t10.*w.*x0-c.*t.*t11.*w.*x0+c.*t0.*t11.*w.*x0+c.*t10.*tf.*w.*x0.*2.0),-t19.*(t2.^2.*t5.*x0.*4.0+c.*t5.*v0-c.*t8.*v0-t2.*t10.*v0.*w.*4.0-c.*t.*t2.*t5.*x0-c.*t0.*t2.*t5.*x0-c.*t.*t2.*t8.*x0+c.*t0.*t2.*t8.*x0+c.*t2.*t5.*tf.*x0.*2.0+c.*t.*t10.*v0.*w+c.*t0.*t10.*v0.*w-c.*t.*t11.*v0.*w+c.*t0.*t11.*v0.*w-c.*t10.*tf.*v0.*w.*2.0)];
