function out1 = LQRScalarTransfer_U(a,b,c,d,f,q,r,t)
%LQRSCALARTRANSFER_U
%    OUT1 = LQRSCALARTRANSFER_U(A,B,C,D,F,Q,R,T)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Mar-2018 19:37:21

t2 = 1.0./r;
t3 = a.^2;
t4 = r.*t3;
t5 = b.^2;
t6 = q.*t5;
t7 = t4+t6;
t8 = r.*t7;
t9 = sqrt(t8);
t10 = f.*t2.*t9.*2.0;
t11 = exp(t10);
t12 = 1.0./b;
t13 = t.*t2.*t9.*-1.0;
t14 = exp(t13);
t15 = t11-1.0;
t16 = 1.0./t15;
t17 = f.*t2.*t9;
t18 = exp(t17);
t19 = t.*t2.*t9.*2.0;
t20 = exp(t19);
t21 = t.*2.0;
t22 = f+t21;
t23 = t2.*t9.*t22;
t24 = exp(t23);
out1 = t12.*t14.*t16.*(a.*c.*t11-a.*c.*t20.*1.0-a.*d.*t18.*1.0+a.*d.*t24).*-1.0-t2.*t12.*t14.*t16.*(c.*t9.*t11+c.*t9.*t20-d.*t9.*t18.*1.0-d.*t9.*t24.*1.0).*1.0;
