function Y = LQRScalarTransfer_Y(a,b,c,d,f,q,r,t)
%LQRSCALARTRANSFER_Y
%    Y = LQRSCALARTRANSFER_Y(A,B,C,D,F,Q,R,T)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Mar-2018 19:37:21

t2 = 1.0./r;
t3 = a.^2;
t4 = r.^2;
t5 = t3.*t4;
t6 = b.^2;
t7 = q.*r.*t6;
t8 = t5+t7;
t9 = sqrt(t8);
t10 = exp(-t.*t2.*t9);
Y = c.*t10-(t10.*(exp(t.*t2.*t9.*2.0)-1.0).*(c-d.*exp(f.*t2.*t9)))./(exp(f.*t2.*t9.*2.0)-1.0);
