function out1 = BrysonHo116_Y(t,tf,v0,x0)
%BRYSONHO116_Y
%    OUT1 = BRYSONHO116_Y(T,TF,V0,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Dec-2017 14:51:09

t2 = tf.^2;
t3 = v0.^2;
t6 = x0.*4.0;
t15 = tf.*v0.*2.0;
t4 = t2-t3-t6-t15;
t5 = sqrt(t4);
t7 = tf-v0;
t8 = v0.*(1.0./2.0);
t9 = t7.^2;
t17 = t3.*2.0;
t10 = -t6+t9-t17;
t11 = sqrt(t10);
t12 = t11.*(1.0./2.0);
t14 = tf.*(1.0./2.0);
t13 = t8-t12+t14;
t16 = t5.*(1.0./2.0);
t18 = t13.^2;
t19 = t18.*(1.0./2.0);
t20 = t8+t12+t14;
t21 = t-t8-t14+t16;
t22 = heaviside(t21);
t23 = t-tf;
t24 = heaviside(t23);
t25 = t-t8-t14-t16;
t26 = heaviside(t25);
t27 = t24-t26;
t28 = t+1.0;
t29 = heaviside(t28);
t30 = t22-t29;
t31 = t8+t12-t14;
out1 = [-t30.*(x0-t.*(t-v0.*2.0).*(1.0./2.0))-t27.*(t19+x0+t.*(t-tf.*2.0).*(1.0./2.0)+t20.^2.*(1.0./2.0))+(t22-heaviside(t-t5.*(1.0./2.0)-t8-t14)).*(t19+x0+t.*t31),-t23.*t27+t31.*(t22-t26)+t30.*(t-v0)];
