function out1 = Cart_Y(t,tf)
%Cart_Y
%    OUT1 = Cart_Y(T,TF)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Oct-2015 20:13:46

t2 = exp(-t);
t3 = exp(-tf);
t4 = t2.*(1.0./2.0);
t5 = exp(t);
t6 = t5.*(1.0./2.0);
out1 = [t+t2-t3.*(t4+t6-1.0)-1.0,-t2+t3.*(t4-t6)+1.0];
