function I = Cart_F(tf)
%CART_F
%    I = CART_F(TF)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    25-Oct-2015 20:13:46

t2 = exp(-tf);
I = tf.*(-1.0./2.0)-exp(tf.*-2.0).*(1.0./4.0)+t2.*(t2.*(1.0./2.0)+exp(tf).*(1.0./2.0)-1.0)+1.0./4.0;
