function x = DTQP3_Y(a1,a2,b,m,r,t,tf,w1,w2,x0)
%DTQP3_Y
%    X = DTQP3_Y(A1,A2,B,M,R,T,TF,W1,W2,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Jan-2018 23:40:16

t2 = 1.0./w1;
t3 = 1.0./w2;
t4 = tf.*w1;
t5 = cos(t4);
t6 = a1.*t5.*w2;
t7 = tf.*w2;
t8 = cos(t7);
t9 = a2.*t8.*w1;
t10 = b.^2;
t11 = m.*t10.*tf;
x = t2.*t3.*(t6+t9-a1.*w2.*cos(t.*w1)-a2.*w1.*cos(t.*w2))+((x0-t2.*t3.*(t6+t9-a1.*w2-a2.*w1)).*(r+t11-m.*t.*t10))./(r+t11);
