function out1 = JadduShimemura2_parameters
%JADDUSHIMEMURA2_PARAMETERS
%    OUT1 = JADDUSHIMEMURA2_PARAMETERS

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Oct-2019 00:25:28

out1 = [4.685799386485817e-1,-5.027218540085993e-1];
