function u = BettsBiehnCampbell1_U(t)
%BETTSBIEHNCAMPBELL1_U
%    U = BETTSBIEHNCAMPBELL1_U(T)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    17-Dec-2017 22:39:24

t2 = t-4.0;
u = t2.^2.*-1.2e1;
