function out1 = SimpleSASA_P(f,J)
%SIMPLESASA_P
%    OUT1 = SIMPLESASA_P(F,J)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Sep-2020 17:30:21

out1 = J.*1.0./f.^2.*3.41729159389659;
