function out1 = SimpleSASA_Ts(f)
%SIMPLESASA_TS
%    OUT1 = SIMPLESASA_TS(F)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Sep-2020 17:30:22

out1 = (f.*2.289143530753965)./pi;
