function out1 = SimpleSASA_U(t,umax,f)
%SIMPLESASA_U
%    OUT1 = SIMPLESASA_U(T,UMAX,F)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Sep-2020 17:30:21

out1 = -umax.*(heaviside(t-(f.*2.289143530753965)./pi).*2.0-1.0);
