function out1 = SimpleSASA_F(umax,f,J)
%SIMPLESASA_F
%    OUT1 = SIMPLESASA_F(UMAX,F,J)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Sep-2020 17:30:21

out1 = (f.^2.*umax.*3.007828461568226e-1)./J;
