function out1 = SimpleSASA_Y2(t,umax,f,J)
%SIMPLESASA_Y2
%    OUT1 = SIMPLESASA_Y2(T,UMAX,F,J)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    04-Sep-2020 17:30:22

t2 = 1.0./pi;
t3 = 1.0./f;
t4 = -t;
t5 = pi.*-5.88425041228374e-1i;
t6 = pi.*5.88425041228374e-1i;
t7 = f.*t2.*-2.289143530753965;
t8 = f.*t2.*2.289143530753965;
t10 = t.*t3.*t5;
t11 = t.*t3.*t6;
t9 = t+t7;
t13 = exp(t10);
t14 = exp(t11);
t15 = t4+t8;
t19 = t5+t11;
t20 = t6+t10;
t12 = dirac(t9);
t16 = heaviside(t15);
t17 = t14-1.0;
t21 = exp(t19);
t22 = exp(t20);
t18 = t17.^2;
out1 = real((1.0./t3.^2.*umax.*(heaviside(t9).*(t3.*t21.*pi.*6.89250983447853i-t3.*t22.*pi.*6.89250983447853i)+t12.*(t21.*1.171348829765978e+1+t22.*1.171348829765978e+1-1.155254578651332e+1).*1.0+t12.*t13.*t18.*5.776272893256659-t3.*t16.*t17.*pi.*6.797807230721777i+t3.*t13.*t16.*t18.*pi.*3.398903615360888i))./J).*2.533029591058444e-2;
