function C1 = LQRScalar_C1(a,b,q,r)
%LQRSCALAR_C1
%    C1 = LQRSCALAR_C1(A,B,Q,R)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Apr-2018 20:29:22

C1 = sqrt(a.^2.*r+b.^2.*q);
