function solu = LinearPendulum_U(m,k,umax,tf,t)
%LINEARPENDULUM_U
%    SOLU = LINEARPENDULUM_U(M,K,UMAX,TF,T)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:08:54

solu = -umax.*sign(sin(sqrt(k).*1.0./sqrt(m).*(t-tf)));
