function solx = LinearPendulum_Y1(s,t0,x0,v0,t)
%LINEARPENDULUM_Y1
%    SOLX = LINEARPENDULUM_Y1(S,T0,X0,V0,T)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:08:54

t2 = -t0;
t3 = t+t2;
t4 = cos(t3);
solx = t4.*x0-sign(s).*(t4./2.0-1.0./2.0).*2.0+v0.*sin(t3);
