function u = BrysonHo166_U(t,tf,v0,x0)
%BRYSONHO166_U
%    U = BRYSONHO166_U(T,TF,V0,X0)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    22-Oct-2015 00:01:00

t2 = t-tf;
t3 = sin(tf);
u = -(t3.*(v0.*cos(t2).*2.0+x0.*sin(t2).*2.0)-tf.*(v0.*cos(t).*2.0-x0.*sin(t).*2.0))./(t3.^2-tf.^2);
