function u = MineExtraction_U(t,a,T,x0)
%MINEEXTRACTION_U
%    U = MINEEXTRACTION_U(T,A,T,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-Mar-2021 23:43:31

t2 = T.*a;
u = a.*x0.*1.0./(t2+4.0).^2.*(t2-a.*t+4.0).*2.0;
