function I = MineExtraction_F(t,a,T,x0)
%MINEEXTRACTION_F
%    I = MINEEXTRACTION_F(T,A,T,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    25-Mar-2021 23:43:31

t2 = T.*a;
I = -(a.*t2.*x0)./(t2+4.0);
