function Y = HagerHouRao1_Y(t)
%HAGERHOURAO1_Y
%    Y = HAGERHOURAO1_Y(T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Dec-2020 10:33:00

t2 = t-1.0;
t3 = cosh(t2);
Y = [t3.*exp(t.*(-3.0./2.0)).*(exp(t.*3.0).*2.0+2.008553692318767e+1).*2.934292591200223e-2,1.543080634815244./t3];
