function out1 = JadduShimemura3_parameters
%JADDUSHIMEMURA3_PARAMETERS
%    OUT1 = JADDUSHIMEMURA3_PARAMETERS

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Oct-2019 00:50:07

out1 = 6.445568238971056e-1;
