function I = DTQP3_F(a1,a2,b,m,r,tf,w1,w2,x0)
%DTQP3_F
%    I = DTQP3_F(A1,A2,B,M,R,TF,W1,W2,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Jan-2018 23:40:16

t2 = b.^2;
t3 = m.*t2.*tf;
t4 = sin(tf.*w1.*(1.0./2.0));
t5 = sin(tf.*w2.*(1.0./2.0));
t6 = a1.*t4.^2.*w2.*2.0+a2.*t5.^2.*w1.*2.0+w1.*w2.*x0;
I = m.*t6.^2.*1.0./w1.^2.*1.0./w2.^2.*1.0./(r+t3).^2.*(t3+r.^2);
