function U_t2 = JadduShimemura1_U_t2(t)
%JADDUSHIMEMURA1_U_T2
%    U_T2 = JADDUSHIMEMURA1_U_T2(T)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Oct-2019 20:05:45

U_t2 = t.*1.6e+1+(t-1.0./2.0).^2.*8.0-1.7e+1./2.0;
