function u = BrysonHo156_U(c,t,t0,tf,v0,w,x0)
%BRYSONHO156_U
%    U = BRYSONHO156_U(C,T,T0,TF,V0,W,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Dec-2017 11:48:06

t2 = t0-tf;
t3 = t2.*w;
t4 = t2.*w.*2.0;
t5 = w.^2;
u = (sin(w.*(t-tf)).*(t5.*x0.*cos(t3).*4.0-v0.*w.*sin(t3).*4.0))./(-t4+sin(t4)+(t5.*w.*4.0)./c);
