function y1 = Nonlinear1D_Y(t)
%NONLINEAR1D_Y
%    Y1 = NONLINEAR1D_Y(T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Dec-2020 11:18:26

t2 = t.*2.0;
t3 = sqrt(2.0);
y1 = exp(-t3.*(t2-1.0e+1)).*(exp(t3.*(t2-5.0)).*7.066818631437233e-1+1.0).^2.*1.440978027414308e-6;
