function F = Nonlinear1D_F(t)
%NONLINEAR1D_F
%    F = NONLINEAR1D_F(T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Dec-2020 11:18:26

t2 = sqrt(2.0);
F = (t2.*4.751785916162887e+29+1.58646708497826e+29).*(exp(t2.*1.0e+1)-1.0).*2.273462462219277e-36;
