function out1 = JadduShimemura1_parameters
%JADDUSHIMEMURA1_PARAMETERS
%    OUT1 = JADDUSHIMEMURA1_PARAMETERS

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Oct-2019 22:38:00

out1 = [2.901127096878842e-1,7.012788621191859e-1,-5.833986476063728e-2];
