function F = SecondOrderSingular_F
%SecondOrderSingular_F
%    F = SecondOrderSingular_F

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    13-Apr-2024 11:42:22

F = 3.769919302879714e-1;
end
