function out1 = SecondOrderSingular_Y(t)
%SecondOrderSingular_Y
%    OUT1 = SecondOrderSingular_Y(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    13-Apr-2024 11:42:22

t2 = exp(t);
t3 = -t;
t5 = exp(1.413764078465027);
t6 = exp(-1.413764078465027);
t7 = t-1.413764078465027;
t4 = exp(t3);
t8 = heaviside(t7);
t9 = t3+1.413764078465027;
t11 = t2.*t6.*3.177826104831298e-4;
t10 = heaviside(t9);
t12 = t4.*t5.*4.140818610755103e-1;
et1 = sinh(t.*2.0-2.827528156930054).*8.573194432877287e-2;
et2 = sinh(t7).^2.*(-1.714636866859707e-1);
et3 = 2.912600842590228e-1;
out1 = [t8.*(t11+t12)-(t.*t10.*(t-2.0))./2.0,t8.*(t11-t12)-t10.*(t-1.0),t8.*(et1+et2+et3)+t10.*(t./2.0-t.^2./2.0+t.^3./3.0-t.^4./8.0+t.^5./4.0e+1)];
end
