function out1 = SecondOrderSingular_U(t)
%SecondOrderSingular_U
%    OUT1 = SecondOrderSingular_U(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    13-Apr-2024 11:42:22

t2 = -t;
et1 = exp(-1.413764078465027).*exp(t).*3.177826104831298e-4;
et2 = exp(1.413764078465027).*exp(t2).*4.140818610755103e-1;
out1 = -heaviside(t2+1.413764078465027)+heaviside(t-1.413764078465027).*(et1+et2);
end
