function L = DTQP2_L(A,B,M,R,t,tf,w,x0)
%DTQP2_L
%    L = DTQP2_L(A,B,M,R,T,TF,W,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Jan-2018 23:10:02

t2 = sin(t.*w);
t3 = A.^2;
t5 = w.^2;
t4 = t3+t5;
t6 = A.*t;
t7 = exp(t6);
t8 = B.^2;
t9 = tf.*w.*2.0;
L = M.^2.*t2.^2.*t3.*t4.^2.*t8.*x0.^2.*exp(A.*tf.*4.0).*1.0./(-M.*t3.*t7.*t8-M.*t5.*t7.*t8+M.*t5.*t8.*exp(A.*(t+tf.*2.0))+A.*R.*t3.*t7.*4.0+A.*R.*t5.*t7.*4.0+M.*t3.*t7.*t8.*cos(t9)-A.*M.*t7.*t8.*w.*sin(t9)).^2.*1.6e1;
