function u = DTQP2_U(A,B,M,R,t,tf,w,x0)
%DTQP2_U
%    U = DTQP2_U(A,B,M,R,T,TF,W,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    15-Jan-2018 23:10:01

t2 = A.^2;
t3 = w.^2;
t4 = A.*t;
t5 = exp(t4);
t6 = B.^2;
t7 = tf.*w.*2.0;
u = (A.*B.*M.*x0.*exp(A.*tf.*2.0).*sin(t.*w).*(t2+t3).*-4.0)./(-M.*t2.*t5.*t6-M.*t3.*t5.*t6+M.*t3.*t6.*exp(A.*(t+tf.*2.0))+A.*R.*t2.*t5.*4.0+A.*R.*t3.*t5.*4.0+M.*t2.*t5.*t6.*cos(t7)-A.*M.*t5.*t6.*w.*sin(t7));
