function F = LQRScalarTransfer_F(a,b,c,d,f,q,r)
%LQRScalarTransfer_F
%    F = LQRScalarTransfer_F(A,B,C,D,f,Q,R)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Jun-2023 15:53:43

t2 = a.^2;
t3 = b.^2;
t4 = c.^2;
t5 = d.^2;
t6 = r.^2;
t8 = 1.0./r;
t7 = 1.0./t3;
t9 = q.*r.*t3;
t10 = t2.*t6;
t11 = t9+t10;
t12 = sqrt(t11);
F = t7.*(t12.*(t4+t5)+a.*r.*(t4-t5))+(t7.*t12.*(t4.*2.0+t5.*2.0-c.*d.*exp(f.*t8.*t12).*4.0))./(exp(f.*t8.*t12.*2.0)-1.0);
