function Y = LQRScalarTransfer_Y(a,b,c,d,f,q,r,t)
%LQRScalarTransfer_Y
%    Y = LQRScalarTransfer_Y(A,B,C,D,F,Q,R,T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Jun-2023 15:53:43

t2 = a.^2;
t3 = b.^2;
t4 = r.^2;
t5 = 1.0./r;
t6 = q.*r.*t3;
t7 = t2.*t4;
t8 = t6+t7;
t9 = sqrt(t8);
t10 = t.*t5.*t9;
t11 = -t10;
t12 = exp(t11);
Y = c.*t12-(t12.*(exp(t10.*2.0)-1.0).*(c-d.*exp(f.*t5.*t9)))./(exp(f.*t5.*t9.*2.0)-1.0);
