function out1 = LQRScalarTransfer_U(a,b,c,d,f,q,r,t)
%LQRScalarTransfer_U
%    OUT1 = LQRScalarTransfer_U(A,B,C,D,F,Q,R,T)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    07-Jun-2023 15:53:43

t2 = t.*2.0;
t3 = a.^2;
t4 = b.^2;
t5 = 1.0./b;
t6 = 1.0./r;
t7 = r.*t3;
t8 = q.*t4;
t9 = f+t2;
t10 = t7+t8;
t11 = r.*t10;
t12 = sqrt(t11);
t13 = f.*t6.*t12;
t15 = t.*t6.*t12.*-1.0;
t16 = t.*t6.*t12.*1.0;
t17 = t2.*t6.*t12;
t23 = t6.*t9.*t12;
t14 = t13.*2.0;
t18 = exp(t13);
t20 = exp(t15);
t21 = exp(t17);
t24 = exp(t23);
t19 = exp(t14);
t22 = t19-1.0;
t25 = 1.0./t22;
out1 = t5.*t20.*t25.*(a.*c.*t19-a.*c.*t21.*1.0-a.*d.*t18.*1.0+a.*d.*t24).*-1.0-t5.*t6.*t20.*t25.*(c.*t12.*t19+c.*t12.*t21-d.*t12.*t18.*1.0-d.*t12.*t24.*1.0).*1.0;
