function Y1t = MultiphaseParameter_Y1(P,t,in3)
%MULTIPHASEPARAMETER_Y1
%    Y1T = MULTIPHASEPARAMETER_Y1(P,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 23:44:59

y01 = in3(1,:);
y02 = in3(2,:);
y03 = in3(3,:);
y04 = in3(4,:);
y05 = in3(5,:);
y06 = in3(6,:);
t2 = t.^2;
t3 = t2.^2;
t4 = exp(-t);
t5 = exp(t);
t6 = P.*t5.*2.0;
Y1t = [t4.*(P.*-3.6e2+y01.*1.2e2-P.*t.*2.4e2-P.*t2.*1.2e2-P.*t3.*1.0e1+P.*t5.*3.6e2+t.*y02.*1.2e2+t2.*y03.*6.0e1+t3.*y05.*5.0-P.*t.*t2.*2.0e1-P.*t.*t3+t.*t2.*y04.*2.0e1+t.*t3.*y06).*(1.0./1.2e2);t4.*(P.*-4.8e1+y02.*2.4e1-P.*t.*4.8e1-P.*t2.*1.2e1-P.*t3+P.*t5.*4.8e1+t.*y03.*2.4e1+t2.*y04.*1.2e1+t3.*y06-P.*t.*t2.*8.0+t.*t2.*y05.*4.0).*(1.0./2.4e1);t4.*(P.*-1.2e1+y03.*6.0-P.*t.*6.0-P.*t2.*6.0+P.*t5.*1.2e1+t.*y04.*6.0+t2.*y05.*3.0-P.*t.*t2+t.*t2.*y06).*(1.0./6.0);t4.*(P.*-2.0+t6+y04.*2.0-P.*t.*4.0-P.*t2+t.*y05.*2.0+t2.*y06).*(1.0./2.0);t4.*(P.*-2.0+t6+y05-P.*t+t.*y06);t4.*y06-P.*(t4-1.0)];
