function F3 = MultiphaseParameter_F3(P,tf2,tf3,in4)
%MULTIPHASEPARAMETER_F3
%    F3 = MULTIPHASEPARAMETER_F3(P,TF2,TF3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    10-May-2018 23:44:58

y01 = in4(1,:);
y02 = in4(2,:);
y03 = in4(3,:);
y04 = in4(4,:);
y05 = in4(5,:);
y06 = in4(6,:);
t2 = P+y04;
t3 = tf2.*2.0;
t8 = tf3.*2.0;
t4 = t3-t8;
t5 = exp(t4);
t6 = P.^2;
t7 = t2.^2;
t9 = P-y01;
t10 = P-y03;
t11 = P-y05;
t12 = P-y06;
t13 = t9.^2;
t14 = t10.^2;
t15 = t11.^2;
t16 = t12.^2;
t17 = tf2-tf3;
t18 = exp(t17);
F3 = t7.*(1.0./2.0)+t13.*(1.0./2.0)+t14.*(1.0./2.0)+t15.*(1.0./2.0)+t16.*(1.0./2.0)-P.*t2.*2.0-P.*t9.*2.0-P.*t10.*2.0-P.*t11.*2.0-P.*t12.*2.0-t5.*t7.*(1.0./2.0)-t5.*t13.*(1.0./2.0)-t5.*t14.*(1.0./2.0)-t5.*t15.*(1.0./2.0)-t5.*t16.*(1.0./2.0)-t6.*tf2.*5.0+t6.*tf3.*5.0-y02.^2.*(t5.*(1.0./2.0)-1.0./2.0)+P.*t2.*t18.*2.0+P.*t9.*t18.*2.0+P.*t10.*t18.*2.0+P.*t11.*t18.*2.0+P.*t12.*t18.*2.0;
