function U = JadduShimemura0_U(t)
%JADDUSHIMEMURA0_U
%    U = JADDUSHIMEMURA0_U(T)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Oct-2019 14:50:35

t2 = exp(1.0);
t3 = exp(2.0);
t4 = exp(t);
t5 = sqrt(2.0);
t6 = t5.*1.0e+1;
t7 = t5.*2.0e+1;
t13 = t.*t5.*-1.0e+1;
t8 = exp(t7);
t9 = t.*t6;
t10 = t6+1.0;
t12 = t7+2.0;
t18 = t6+t13;
t11 = t10+1.0;
t14 = exp(t9);
t15 = exp(t10);
t17 = exp(t12);
t19 = exp(t18);
t16 = exp(t11);
U = ((t4-t4.*t5.*1.0e+1+t4.*t8+t3.*t14-t4.*t15.*2.0+t5.*t14.*9.95e+2-t2.*t19-t14.*t15+t16.*t19-t5.*t19.*exp(t6).*9.95e+2+t4.*t6.*t8+t3.*t5.*t14.*9.9505e+2+t2.*t6.*t19-t5.*t14.*t15.*1.0e+1-t5.*t16.*t19.*9.9505e+2).*-2.0e+2)./(t3.*1.9901e+4-t5.*2.0e+3+t8.*2.01e+4-t15.*8.0e+2+t17.*1.9901e+4+t3.*t6+t5.*t8.*2.0e+3-t5.*t17.*1.0e+1+2.01e+4);
