function out1 = JadduShimemura0_F
%JADDUSHIMEMURA0_F
%    OUT1 = JADDUSHIMEMURA0_F

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    22-Oct-2019 14:50:36

out1 = 6.936094371820911e-2;
