function I = LQRScalar_F(a,b,c1,c2,c3,m,q,r,t0,tf)
%LQRSCALAR_F
%    I = LQRSCALAR_F(A,B,C1,C2,C3,M,Q,R,T0,TF)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Apr-2018 20:29:22

t3 = 1.0./sqrt(r);
t4 = c1.*tf;
t5 = c2+t4;
t19 = t3.*t5;
t2 = cosh(t19);
t6 = sqrt(r);
t7 = 1.0./c1;
t8 = c3.^2;
t9 = c1.^2;
t10 = t3.*t5.*2.0;
t11 = sinh(t10);
t12 = a.^2;
t13 = r.^(3.0./2.0);
t14 = c2.*2.0;
t15 = c1.*t0.*2.0;
t16 = t14+t15;
t17 = t3.*t16;
t18 = sinh(t17);
t20 = t2.^2;
t21 = cosh(t3.*t16.*(1.0./2.0));
I = t7.*t8.*(c1.*m.*t20.*4.0-c1.*q.*t0.*2.0+c1.*q.*tf.*2.0+q.*t6.*t11-q.*t6.*t18).*(1.0./4.0)+1.0./b.^2.*t7.*t8.*(c1.*t0.*t9.*2.0-c1.*t9.*tf.*2.0+t6.*t9.*t11-t6.*t9.*t18+t11.*t12.*t13-t12.*t13.*t18-a.*c1.*r.*t20.*4.0-c1.*r.*t0.*t12.*2.0+c1.*r.*t12.*tf.*2.0+a.*c1.*r.*t21.^2.*4.0).*(1.0./4.0);
