function x = LQRScalar_Y(c1,c2,c3,r,t)
%LQRSCALAR_Y
%    X = LQRSCALAR_Y(C1,C2,C3,R,T)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Apr-2018 20:29:22

x = c3.*cosh(1.0./sqrt(r).*(c2+c1.*t));
