function C2 = LQRScalar_C2(a,b,c1,m,r,tf)
%LQRSCALAR_C2
%    C2 = LQRSCALAR_C2(A,B,C1,M,R,TF)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    30-Apr-2018 20:29:22

C2 = -c1.*tf+sqrt(r).*atanh((1.0./sqrt(r).*(a.*r-b.^2.*m))./c1);
