function u = LQRScalar_U(a,b,c1,c2,c3,r,t)
%LQRSCALAR_U
%    U = LQRSCALAR_U(A,B,C1,C2,C3,R,T)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Jan-2018 13:03:11

t2 = 1.0./b;
t3 = 1.0./sqrt(r);
t4 = c1.*t;
t5 = c2+t4;
t6 = t3.*t5;
u = -a.*c3.*t2.*cosh(t6)+c1.*c3.*t2.*t3.*sinh(t6);
