function C3 = LQRScalar_C3(c1,c2,r,t0,x0)
%LQRSCALAR_C3
%    C3 = LQRSCALAR_C3(C1,C2,R,T0,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    16-Jan-2018 13:03:12

C3 = x0./cosh(1.0./sqrt(r).*(c2+c1.*t0));
