function F = SecondOrderSingular_F
%SECONDORDERSINGULAR_F
%    F = SECONDORDERSINGULAR_F

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Sep-2020 01:42:09

F = 3.769919302879714e-1;
