function out1 = SecondOrderSingular_Y(t)
%SECONDORDERSINGULAR_Y
%    OUT1 = SECONDORDERSINGULAR_Y(T)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-Sep-2020 01:42:09

t2 = exp(t);
t3 = -t;
t5 = exp(1.413764078465027);
t7 = t-1.413764078465027;
t4 = 1.0./t2;
t6 = 1.0./t5;
t8 = heaviside(t7);
t9 = t3+1.413764078465027;
t10 = heaviside(t9);
t11 = t2.*t6.*3.177826104831298e-4;
t12 = t4.*t5.*4.140818610755103e-1;
out1 = [t8.*(t11+t12)-(t.*t10.*(t-2.0))./2.0,t8.*(t11-t12)-t10.*(t-1.0),t8.*(sinh(t.*2.0-2.827528156930054).*8.573194432877287e-2-sinh(t7).^2.*1.714636866859707e-1+2.912600842590228e-1)+t10.*(t./2.0-t.^2./2.0+t.^3./3.0-t.^4./8.0+t.^5./4.0e+1)];
