function x = BrysonHo153_Y(c,t,t0,tf,x0)
%BRYSONHO153_Y
%    X = BRYSONHO153_Y(C,T,T0,TF,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Dec-2017 11:31:19

x = x0+(c.*x0.*(t-t0))./(c.*(t0-tf)-1.0);
