function u = BrysonHo153_U(c,t0,tf,x0)
%BRYSONHO153_U
%    U = BRYSONHO153_U(C,T0,TF,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Dec-2017 11:31:19

u = -x0./(-t0+tf+1.0./c);
