function x = AndersonMoore64_Y(t,t0,tf,x0)
%ANDERSONMOORE64_Y
%    X = ANDERSONMOORE64_Y(T,T0,TF,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Dec-2017 10:16:21

x = (x0.*(exp(t-tf)+1.0))./(exp(t0-tf)+1.0);
