function I = AndersonMoore64_F(t0,tf,x0)
%ANDERSONMOORE64_F
%    I = ANDERSONMOORE64_F(T0,TF,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    14-Dec-2017 10:16:21

I = -(x0.^2.*exp(-t0).*(exp(t0-tf.*2.0).*exp(t0)-1.0))./(exp(t0-tf).*2.0+exp(t0.*2.0-tf.*2.0)+1.0);
