function u1 = Nonlinear1D_U(t)
%NONLINEAR1D_U
%    U1 = NONLINEAR1D_U(T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Dec-2020 11:18:26

t2 = t.*2.0;
t3 = sqrt(2.0);
t4 = t2-5.0;
t5 = t4-5.0;
t6 = t3.*t4;
t7 = exp(t6);
t8 = t3.*t5;
t9 = -t8;
t11 = t7.*7.066818631437233e-1;
t10 = exp(t9);
t12 = t11+1.0;
t13 = t12.^2;
u1 = 1.0./sqrt(t10.*t13.*1.440978027414308e-6).*(t10.*t13.*2.881956054828615e-6+t3.*t10.*t13.*2.881956054828615e-6-t3.*t7.*t10.*t12.*4.07325214864924e-6).*(-1.0./2.0);
