function solDx = LinearPendulum_Y2(s,t0,x0,v0,t)
%LINEARPENDULUM_Y2
%    SOLDX = LINEARPENDULUM_Y2(S,T0,X0,V0,T)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:08:54

t2 = -t0;
t3 = t+t2;
t4 = sin(t3);
solDx = -t4.*x0+v0.*cos(t3)+t4.*sign(s);
