function F = HagerHouRao1_F(t)
%HAGERHOURAO1_F
%    F = HAGERHOURAO1_F(T)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Dec-2020 10:33:00

F = exp(-2.0).*(-1.049935854035065e-1)+exp(2.0).*1.049935854035065e-1-exp(-3.0).*1.654173135087694+exp(3.0).*8.200570518363271e-3+1.645972564569331;
