function out1 = SimpleSASA_U(t,umax,f)
%SimpleSASA_U
%    OUT1 = SimpleSASA_U(T,UMAX,F)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Apr-2024 12:29:24

out1 = -umax.*(heaviside(t-(f.*2.289143530753965)./pi).*2.0-1.0);
end
