function out1 = SimpleSASA_F(umax,f,J)
%SimpleSASA_F
%    OUT1 = SimpleSASA_F(UMAX,F,J)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Apr-2024 12:29:24

out1 = (f.^2.*umax.*3.007828461568226e-1)./J;
end
