function out1 = SimpleSASA_P(f,J)
%SimpleSASA_P
%    OUT1 = SimpleSASA_P(F,J)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Apr-2024 12:29:24

out1 = J.*1.0./f.^2.*3.41729159389659;
end
