function out1 = SimpleSASA_Ts(f)
%SimpleSASA_Ts
%    OUT1 = SimpleSASA_Ts(F)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Apr-2024 12:29:24

out1 = (f.*2.289143530753965)./pi;
end
