function out1 = SimpleSASA_Y1(t,umax,f,J)
%SimpleSASA_Y1
%    OUT1 = SimpleSASA_Y1(T,UMAX,F,J)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    14-Apr-2024 12:29:24

t2 = 1.0./pi;
t3 = 1.0./f;
t4 = pi.*5.88425041228374e-1i;
t5 = f.*t2.*2.289143530753965;
t6 = t.*t3.*pi.*-5.88425041228374e-1i;
t7 = t.*t3.*t4;
out1 = real((1.0./t3.^2.*umax.*(heaviside(t-t5).*(exp(-t4+t7).*1.171348829765978e+1+exp(t4+t6).*1.171348829765978e+1-1.155254578651332e+1)-heaviside(-t+t5).*exp(t6).*(exp(t7)-1.0).^2.*5.776272893256659))./J).*2.533029591058444e-2;
end
