function I = BrysonHo154_F(c1,c2,t0,tf,v0,x0)
%BRYSONHO154_F
%    I = BRYSONHO154_F(C1,C2,T0,TF,V0,X0)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    19-Dec-2017 12:06:01

t2 = tf.^2;
t3 = t0.^2;
t4 = v0.^2;
t5 = x0.^2;
I = (c1.*t4.*6.0+c2.*t5.*6.0+c2.*t2.*t4.*6.0+c2.*t3.*t4.*6.0-c1.*c2.*t0.*t5.*6.0+c1.*c2.*t5.*tf.*6.0-c2.*t0.*t4.*tf.*1.2e1-c2.*t0.*v0.*x0.*1.2e1+c2.*tf.*v0.*x0.*1.2e1-c1.*c2.*t0.*t2.*t4.*6.0-c1.*c2.*t0.*t3.*t4.*2.0+c1.*c2.*t2.*t4.*tf.*2.0+c1.*c2.*t3.*t4.*tf.*6.0+c1.*c2.*t2.*v0.*x0.*6.0+c1.*c2.*t3.*v0.*x0.*6.0-c1.*c2.*t0.*tf.*v0.*x0.*1.2e1)./(t3.*(c2.*tf.*1.2e1+c1.*c2.*t2.*6.0)+c1.*tf.*1.2e1-t0.*(c1.*1.2e1+c2.*t2.*1.2e1+c1.*c2.*t2.*tf.*4.0)-t0.*t3.*(c2.*4.0+c1.*c2.*tf.*4.0)+c2.*t2.*tf.*4.0+c1.*c2.*t2.^2+c1.*c2.*t3.^2+1.2e1);
